name: PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 'Build, Linting and Code Quality Check'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write
      run: |
        echo "vada" | base64 > cert.base64
        gh secret set CERTIFICATE_BASE64 < cert.base64

    - name: Read
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        echo $CERTIFICATE_BASE64 | base64 --decode > cert.der

    - name: jq test
      run: |
        echo '{"data": [1, 2, 3]}' | jq
